<?php

namespace AppBundle\Repository;

/**
 * FigureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigureRepository extends \Doctrine\ORM\EntityRepository
{

    public function findWithImages($id)
    {
        return $this->createQueryBuilder('e')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->innerJoin('e.images', 'img')
            ->addSelect('img')
            ->getQuery()
            ->getOneOrNullResult();


    }
}
