<?php

namespace AppBundle\Repository;

/**
 * FigureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigureRepository extends \Doctrine\ORM\EntityRepository
{

    public function findWithAll($id)
    {
        return $this->createQueryBuilder('e')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->innerJoin('e.images', 'images')
            ->addSelect('images')
            ->leftJoin('e.videos', 'videos')
            ->addSelect('videos')
            ->getQuery()
            ->getOneOrNullResult();
    }

}
