<?php

namespace AppBundle\Repository;

/**
 * GroupFigureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupFigureRepository extends \Doctrine\ORM\EntityRepository
{
}
