<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getForNews($max)
    {
        return $query = $this->createQueryBuilder('m')
            ->innerJoin('m.figure', 'figure')
            ->addSelect('figure')
            ->orderBy('m.dateCreate', 'DESC')
            ->getQuery()
            ->setMaxResults($max)
            ->getResult();
    }

    public function findByFigureWithOrderByDateCreate($figure, $page, $nbPerPage){
         $query = $this->createQueryBuilder('m')
            ->where('m.figure = :id_figure')
            ->setParameter('id_figure', $figure)
            ->orderBy('m.dateCreate', 'DESC')
            ->getQuery();

         $query
             ->setFirstResult(($page-1) * $nbPerPage)
             ->setMaxResults($nbPerPage);

         return new Paginator($query, true);
    }
}
