<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getForNews($max)
    {
        return $query = $this->createQueryBuilder('m')
            ->innerJoin('m.figure', 'figure')
            ->addSelect('figure')
            ->orderBy('m.dateCreate', 'DESC')
            ->getQuery()
            ->setMaxResults($max)
            ->getResult();
    }
}
