security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt


    providers:
        snowtricks:
            entity:
                class: AppBundle:User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
            provider: snowtricks
            logout:
                path: /logout
                target: /
