parameters:

services:
    app.figure_manager:
        class: AppBundle\Manager\FigureManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.password_encoder"

    app.comment_manager:
        class: AppBundle\Manager\CommentManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.groupFigure_manager:
        class: AppBundle\Manager\GroupFigureManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.image_manager:
        class: AppBundle\Manager\ImageManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.video_manager:
        class: AppBundle\Manager\VideoManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.avatar_manager:
        class: AppBundle\Manager\AvatarManager
        arguments:
            - "@doctrine.orm.entity_manager"